
# wrangler.toml

name = "agienginex"
main = "server/index.ts"
compatibility_date = "2024-06-01"

[vars]
OPENAI_API_KEY = ""
SUPABASE_URL = ""
SUPABASE_KEY = ""

[[routes]]
pattern = "agienginex.*.workers.dev/*"
custom_domain = false

[build]
command = ""

[env.production]
name = "agienginex"

[env.staging]
name = "agienginex-staging"
